(function() {var implementors = {};
implementors["scaleless_music"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='scaleless_music/sound/interval/struct.Interval.html' title='scaleless_music::sound::interval::Interval'>Interval</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='scaleless_music/sound/frequency/struct.Vibrato.html' title='scaleless_music::sound::frequency::Vibrato'>Vibrato</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='scaleless_music/sound/wave/struct.Wave.html' title='scaleless_music::sound::wave::Wave'>Wave</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='scaleless_music/sound/rhythm/struct.Tempo.html' title='scaleless_music::sound::rhythm::Tempo'>Tempo</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='scaleless_music/sound/rhythm/struct.TempoChangeLinear.html' title='scaleless_music::sound::rhythm::TempoChangeLinear'>TempoChangeLinear</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='scaleless_music/sound/rhythm/struct.NoteValue.html' title='scaleless_music::sound::rhythm::NoteValue'>NoteValue</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='scaleless_music/sound/timing/enum.TimingOption.html' title='scaleless_music::sound::timing::TimingOption'>TimingOption</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='scaleless_music/sound/backend_portaudio/enum.BackendError.html' title='scaleless_music::sound::backend_portaudio::BackendError'>BackendError</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
