(function() {var implementors = {};
implementors["scaleless_music"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='enum' href='scaleless_music/sound/backend_portaudio/enum.BackendError.html' title='scaleless_music::sound::backend_portaudio::BackendError'>BackendError</a>&gt; for <a class='enum' href='scaleless_music/sound/errors/enum.Error.html' title='scaleless_music::sound::errors::Error'>Error</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='struct' href='scaleless_music/sound/interval/struct.Interval.html' title='scaleless_music::sound::interval::Interval'>Interval</a>&gt; for <a class='type' href='scaleless_music/sound/type.SampleCalc.html' title='scaleless_music::sound::SampleCalc'>SampleCalc</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='struct' href='scaleless_music/sound/rhythm/struct.NoteValue.html' title='scaleless_music::sound::rhythm::NoteValue'>NoteValue</a>&gt; for <a class='type' href='scaleless_music/sound/type.SampleCalc.html' title='scaleless_music::sound::SampleCalc'>SampleCalc</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='struct' href='scaleless_music/sound/progress/struct.ProgressTime.html' title='scaleless_music::sound::progress::ProgressTime'>ProgressTime</a>&gt; for <a class='enum' href='scaleless_music/sound/progress/enum.ProgressOption.html' title='scaleless_music::sound::progress::ProgressOption'>ProgressOption</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='struct' href='scaleless_music/sound/progress/struct.ProgressTempo.html' title='scaleless_music::sound::progress::ProgressTempo'>ProgressTempo</a>&gt; for <a class='enum' href='scaleless_music/sound/progress/enum.ProgressOption.html' title='scaleless_music::sound::progress::ProgressOption'>ProgressOption</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;Error&gt; for <a class='enum' href='scaleless_music/sound/backend_portaudio/enum.BackendError.html' title='scaleless_music::sound::backend_portaudio::BackendError'>BackendError</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
